version: "3.4"

services:
  # database service
  db:
    image: mariadb:latest
    env_file:
      - .env/local.env
    volumes:
      - dbg-sql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dbg-net

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: database_password
    networks:
      - dbg-net


  # wordpress
  wp:
    env_file:
      - .env/local.env
    environment:
      WORDPRESS_DB_HOST: db
      DB_HOST: db
    build:
      dockerfile: docker/wp.local.Dockerfile
      context: "."
    # mounting local volume for hot-reload
    volumes:
      - ./site:/site
      - ./media:/site/web/app/uploads
      - ./uploads.ini:/etc/php7/conf.d/uploads.ini
      - /var/cache/composer # Composer Cache [See Anonymous Volumes]
    depends_on:
      - db
    ports:
      - "80:8080"
    networks:
      - dbg-net
  # theme
  enterprise-theme:
    build:
      dockerfile: docker/theme.local.Dockerfile
      context: "."
      target: "enterprise-builder"
    # mounting local volume for hot-reload
    # TODO determine npm or yarn and remove one.
    volumes:
      - /theme/node_modules
      - ./site/web/app/themes/enterprise-theme:/theme
    depends_on:
      - wp
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - dbg-net

  division-theme:
    build:
      dockerfile: docker/theme.local.Dockerfile
      context: "."
      target: "division-builder"
    # mounting local volume for hot-reload
    # TODO determine npm or yarn and remove one.
    volumes:
      - /theme/node_modules
      - ./site/web/app/themes/division-theme:/theme
      - /var/cache/yarn
    depends_on:
      - wp
    ports:
      - "3002:3000"
      - "3003:3001"
    networks:
      - dbg-net
networks:
  dbg-net:
volumes:
  dbg-sql-data:
