<?php
/**
 * NYBC Resource Cards fields
 *
 * @file
 * @package NYBC
 */

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_61c9d9597851e',
			'title'                 => 'Resource Cards',
			'fields'                => array(
				array(
					'key'               => 'field_61c9d959d92f5',
					'label'             => 'Cards',
					'name'              => 'cards',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_61c9d95a0127e',
					'min'               => 1,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => 'Add Card',
					'sub_fields'        => array(
						array(
							'key'               => 'field_61c9d95a0127e',
							'label'             => 'Title',
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => 'This field is required',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61c9d9fa99fd1',
							'label'             => 'Image',
							'name'              => 'image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_61c9da1199fd2',
							'label'             => 'Icon',
							'name'              => 'icon',
							'type'              => 'icon-picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'initial_value'     => '',
						),
						array(
							'key'               => 'field_61c9da2f99fd3',
							'label'             => 'Description',
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => 'This field is required',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => 4,
							'new_lines'         => 'br',
						),
						array(
							'key'               => 'field_61c9da5c99fd5',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => 'This field is required',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						array(
							'key'               => 'field_61c9da8e99fd6',
							'label'             => 'More info',
							'name'              => 'more_info',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => 'field_61c9daa399fd7',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => 'Add Info',
							'sub_fields'        => array(
								array(
									'key'               => 'field_61c9daa399fd7',
									'label'             => 'Title',
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => 'This field is required',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61c9dacc99fd8',
									'label'             => 'Description',
									'name'              => 'description',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61c9dae799fd9',
									'label'             => 'Count',
									'name'              => 'count',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/resource-cards',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);

endif;
