---
services:
  web:
    image: tugboatqa/php:7.4.27-fpm-bullseye
    default: true
    depends: mysql
    commands:
      init:
        # Install imagick and zip
        - apt-get update
        - apt-get install -y libmagickwand-dev libzip-dev
        # Install the PHP extensions
        - docker-php-ext-install mysqli exif zip
        - pecl install imagick-beta -y
        - docker-php-ext-enable imagick
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer1 --version=1.10.23
        # Install wp-cli
        - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        - chmod +x wp-cli.phar
        - mv wp-cli.phar /usr/local/bin/wp
        - composer1 install --optimize-autoloader
        # Copy the uploads directory from an external server. The public
        # SSH key found in the Tugboat Repository configuration must be
        # copied to the external server in order to use rsync over SSH.
        - mkdir -p "/var/www/html/web/app/uploads" || /bin/true

      update:
        - wget -O azcopyv10.tar https://aka.ms/downloadazcopy-v10-linux
        - tar -xf azcopyv10.tar
        - ls -ltrh
        - ./azcopy_linux_amd64_10.13.0/azcopy cp "https://$MICROSOFT_AZURE_ACCOUNT_NAME.blob.core.windows.net/$MICROSOFT_AZURE_STORAGES_CONTAINER/*?sv=$MICROSOFT_AZURE_STORAGES_SAS" "/var/www/html/web/app/uploads" --recursive --check-length=false
        - chgrp -R www-data "/var/www/html/web/app/uploads"
        - find "/var/www/html/web/app/uploads" -type d -exec chmod 2775 {} \;
        - find "/var/www/html/web/app/uploads" -type f -exec chmod 0664 {} \;

        # Cleanup
        - apt-get clean
        - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

      build:
        - ls ${TUGBOAT_ROOT}
        - ln -snf "${TUGBOAT_ROOT}/web" "/var/www/html"
        - bash ${TUGBOAT_ROOT}/.tugboat/install_node.sh
        - wp --allow-root --path="/var/www/html" search-replace "${TUGBOAT_BASE_PREVIEW_URL_HOST}" "${TUGBOAT_SERVICE_URL_HOST}" --skip-columns=guid
        - wp --allow-root --path="/var/www/html" search-replace "${MICROSOFT_AZURE_ACCOUNT_NAME}.blob.core.windows.net" "${TUGBOAT_SERVICE_URL_HOST}" --skip-columns=guid

      online:
  mysql:
    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mariadb:10.4.21-focal
    # A set of commands to run while building this service
    commands:
      build:
        - ssh nybc_team@52.87.95.160 "mysqldump --defaults-file=~/.my.cnf -hwordpress-web-db-staging.mysql.database.azure.com db" > db.sql
        - mysql tugboat < ./db.sql
        - rm db.sql
