name: JS Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - '**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site/web/app/themes/enterprise-theme
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
      - run: npm install
      - run: npm run lint-css && pwd
      - name: Reviewdog Stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: '../division-theme/'
          stylelint_config: '.stylelintrc.json'
          stylelint_input: '**/*.scss'
