name: JS Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - '**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site/web/app/themes/enterprise-theme
    steps:
      - uses: actions/checkout@v2
      - name: Reviewdog Stylelint Enterprise
        uses: reviewdog/action-stylelint@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: 'site/web/app/themes/enterprise-theme/'
          stylelint_config: '.stylelintrc.json'
          stylelint_input: '**/*.scss'
      - name: Reviewdog Stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: 'site/web/app/themes/division-theme/'
          stylelint_config: '.stylelintrc.json'
          stylelint_input: '**/*.scss'
