name: CI to Docker Hub

on:
  push:
    branches:
      - develop
env:
  DOCKER_REGISTRY_DEVELOP: "index.docker.io"
  DOCKER_REGISTRY_DEVELOP_USERNAME: "nybcteam"
  DOCKER_REGISTRY_STAGING: "nybcwordpresscontainerregistry.azurecr.io"
  DOCKER_REGISTRY_STAGING_USERNAME: "nybcwordpresscontainerregistry"
  DOCKER_REGISTRY_PRODUCTION: ""
  DOCKER_REGISTRY_PRODUCTION_USERNAME: ""
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into docker registry
        uses: docker/login-action@v1
        with:
          registry: "index.docker.io"
          username: "nybcteam"
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push develop
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/wp.server.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: "nybcteam/nybc-wordpress:develop"
          build-args: |
            ACF_PRO_KEY=${{ secrets.ACF_PRO_KEY }}
            ENVIRONMENT=dev
          secrets: |
            "vaultpass=${{ secrets.VAULTPASS }}"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
