---

on:
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    name: Export
    steps:
      - shell: python
        run: |
          import base64
          encoder = lambda s: base64.b64encode(bytes(s.encode('utf-8'))).decode("utf-8")
          strings = (
            ("ACF_PRO_KEY", "${{ secrets.ACF_PRO_KEY }}"),
            ("VAULTPASS", "${{ secrets.VAULTPASS }}"),
          )
          for s in strings:
            print(f"{s[0]}: {encoder(s[1])}")