name: CI to Docker Hub

on:
  push:
    branches:
      - staging
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://nybcwordpresscontainerregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_4429a6e86cab43c38c4edc1a07292d6e }}
          password: ${{ secrets.AzureAppService_ContainerPassword_90127fcbc2d04da087a5dc70a6e225e0 }}

      -
        name: Build Staging
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/wp.server.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: nybcwordpresscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4429a6e86cab43c38c4edc1a07292d6e }}/nybcteamnybc-wordpress:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            ACF_PRO_KEY=${{ secrets.ACF_PRO_KEY }}
            ENVIRONMENT=dev
          secrets: |
            "vaultpass=${{ secrets.VAULTPASS }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'staging-wordpress-web'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1bea6965de524725b091c49317217825 }}
          images: 'nybcwordpresscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4429a6e86cab43c38c4edc1a07292d6e }}/nybcteamnybc-wordpress:${{ github.sha }}'
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
