name: PHP Code Sniffer
on:
  pull_request:
    paths:
      - 'site/web/app/themes/**.php'
      - '*.php'
jobs:
  phpcs:
    defaults:
      run:
        working-directory: site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v6
        with:
          php_version: '7.4'
          version: '1'

      - name: Validate composer.json and composer.lock
        run: composer update

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Detecting PHP Code Standards Violations
        run: pwd && composer run-script test web/app/themes
