name: WPCS check

on: pull_request

jobs:
  phpcs:
    name: WPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls -ltrh
      - name: WPCS check
        uses: 10up/wpcs-action@stable
